<?php
use CRM_Civirules_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_CiviRules_Rule_Conditions',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CiviRules_Rule_Conditions',
        'label' => E::ts('CiviRules Rule Conditions'),
        'api_entity' => 'CiviRulesRuleCondition',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'condition_link',
            'is_active',
            'condition_id.label',
            'condition_params_display',
            'condition_id',
            'rule_id',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_CiviRules_Rule_Conditions_SearchDisplay_CiviRules_Rule_Conditions',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CiviRules_Rule_Conditions',
        'label' => E::ts('CiviRules Rule Conditions'),
        'saved_search_id.name' => 'CiviRules_Rule_Conditions',
        'type' => 'table',
        'settings' => [
          'description' => '',
          'sort' => [],
          'limit' => 20,
          'pager' => [
            'hide_single' => TRUE,
          ],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'condition_link',
              'dataType' => 'String',
              'label' => E::ts('Link Operator'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'condition_id.label',
              'dataType' => 'String',
              'label' => E::ts('Condition'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'condition_params_display',
              'dataType' => 'String',
              'label' => E::ts('Description'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => 'CiviRulesRuleCondition',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Edit'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'path' => '',
                  'icon' => 'fa-toggle-off',
                  'text' => E::ts('Disable'),
                  'style' => 'default',
                  'condition' => [],
                  'task' => 'disable',
                  'entity' => 'CiviRulesRuleCondition',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'task' => 'enable',
                  'entity' => 'CiviRulesRuleCondition',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-on',
                  'text' => E::ts('Enable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'CiviRulesRuleCondition',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => FALSE,
          'classes' => ['table', 'table-striped'],
          'draggable' => 'weight',
          'toolbar' => [
            [
              'path' => 'civicrm/civirule/form/rule_condition?reset=1&action=add&rid=[rule_id]',
              'icon' => 'fa-plus',
              'text' => E::ts('Add condition'),
              'style' => 'default',
              'condition' => [],
              'task' => '',
              'entity' => '',
              'action' => '',
              'join' => '',
              'target' => 'crm-popup',
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
